name: pr
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test - Unit and Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: gradle test --rerun-tasks
  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get PR number
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ github.token }}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PR_NUMBER', prNumber);
      - name: Run Sonar scan
        run: gradle sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.pullrequest.key=$PR_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
